name: Ad Click Prediction CI

on:
  push:
    branches: [ main ]  # main 브랜치에 코드가 push될 때 실행
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
       
      - name: Run Pytest
        env:
          # 테스트 코드에서 모델을 불러올 때 필요한 정보들
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          # 아까 만든 test.py(또는 tests 폴더)를 실행
          pytest

   
      
